import os
import json
import threading
from flask import Flask
from gtts import gTTS
from moviepy.editor import ImageClip, AudioFileClip
from googleapiclient.discovery import build
from google.oauth2.service_account import Credentials
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
BHA_PIXEL_API_KEY = os.getenv("BHAPIXEL_API_KEY")
GOOGLE_CLIENT_SECRET_JSON = os.getenv("GOOGLE_CLIENT_SECRET_JSON")

# Parse Google client secret JSON
client_secret = json.loads(GOOGLE_CLIENT_SECRET_JSON)

# =========================
# YouTube Upload Function
# =========================
def get_youtube_service():
    credentials = Credentials.from_service_account_info(
        client_secret, scopes=["https://www.googleapis.com/auth/youtube.upload"]
    )
    return build("youtube", "v3", credentials=credentials)

def upload_to_youtube(video_file, title="AI Video", description="Generated by AI", categoryId="22", privacyStatus="public"):
    youtube = get_youtube_service()
    request = youtube.videos().insert(
        part="snippet,status",
        body={
            "snippet": {
                "title": title,
                "description": description,
                "categoryId": categoryId
            },
            "status": {
                "privacyStatus": privacyStatus
            }
        },
        media_body=video_file
    )
    response = request.execute()
    print("Uploaded Video ID:", response["id"])
    return response["id"]

# =========================
# AI Workflow Functions
# =========================
def generate_audio(text, filename="voice.mp3"):
    tts = gTTS(text=text, lang="en")
    tts.save(filename)
    return filename

def generate_video(image_path="assets/temp/sample.jpg", audio_path="voice.mp3", output="final_video.mp4", duration=5):
    clip = ImageClip(image_path, duration=duration)
    audio_clip = AudioFileClip(audio_path)
    clip = clip.set_audio(audio_clip)
    clip.write_videofile(output, fps=24)
    return output

def ai_video_workflow():
    print("AI Video Workflow Started 🚀")
    
    # 1️⃣ Generate audio
    text_to_speak = "Hello! This is the first AI generated video."
    audio_file = generate_audio(text_to_speak)

    # 2️⃣ Generate video
    image_file = "assets/temp/sample.jpg"  # Make sure this image exists
    video_file = generate_video(image_path=image_file, audio_path=audio_file)

    # 3️⃣ Upload to YouTube
    video_id = upload_to_youtube(video_file, title="First AI Video", description="Generated fully by AI")
    print(f"AI Video workflow completed successfully! Video ID: {video_id}")

# =========================
# Flask Web Service
# =========================
app = Flask(__name__)

@app.route("/")
def index():
    # Run AI workflow in background thread
    threading.Thread(target=ai_video_workflow).start()
    return "AI Video Generation Started 🚀 Check logs for progress."

# Start Flask server (Render compatible)
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)
